version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - chrome
    networks:
      - scform-network

  chrome:
    image: browserless/chrome
    ports:
      - "1337:3000"
    networks:
      - scform-network

networks:
  scform-network:
    driver: bridge 